pipeline {
    agent {
        kubernetes {
            yamlFile 'jenkins/jenkins-agents.yml'
        }
    }

    environment {
        K8S_NAMESPACE = 'unknown'
    }

    stages {
        stage('Checkout project') {
            steps {
                script {
                   git branch: 'main', url: 'https://github.com/qanguyen94/booking-ci-cd.git'
                }
            }
        }
        stage('Build project') {
            steps {
                script {
                    sh "echo 'Start building backend'"
                    sh "cd backend && ./gradlew build"
                }
            }
        }
        stage('Build docker image') {
            steps {
                container('docker') {
                    script {
                        env.K8S_NAMESPACE = env.GIT_COMMIT
                        backendImage = docker.build("qanguyen/booking-backend:$env.GIT_COMMIT", "-f backend/Dockerfile ./backend")
                        frontendImage = docker.build("qanguyen/booking-frontend:$env.GIT_COMMIT", "-f frontend/Dockerfile ./frontend")
                    }
                }
            }
        }
        stage('Push image') {
            steps {
                container('docker') {
                    script {
                        // Assume the Docker Hub registry by passing an empty string as the first parameter
                        docker.withRegistry('' , 'dockerhub') {
                            backendImage.push()
                            frontendImage.push()
                        }
                    }
                }
            }
        }
        stage('Deploy kubernetes') {
            steps {
                script {
                    kubernetesDeploy(kubeconfigId: "kube-config", configs: "kubernetes/namespace.yml")
                    kubernetesDeploy(kubeconfigId: "kube-config", configs: "kubernetes")
                }
            }
        }
    }
}
