pipeline {
    agent {
        kubernetes {
            yamlFile 'jenkins/jenkins-agents.yml'
        }
    }

    environment {
        K8S_NAMESPACE = 'unknown'
    }

    stages {
        stage('Checkout project') {
            steps {
                script {
                   git branch: 'main', url: 'https://github.com/qanguyen94/booking-ci-cd.git'
                }
            }
        }
        stage('Build project') {
            steps {
                script {
                    sh "echo 'Start building backend'"
                    sh "cd backend && ./gradlew build"
                }
            }
        }
        stage('Build docker image') {
            steps {
                container('docker') {
                    script {
                        def commitId = sh returnStdout: true, script: 'git rev-parse --short HEAD'
                        env.K8S_NAMESPACE = commitId
                        backendImage = docker.build("qanguyen/booking-backend:$commitId", "-f backend/Dockerfile ./backend")
                        frontendImage = docker.build("qanguyen/booking-frontend:$commitId", "-f frontend/Dockerfile ./frontend")
                    }
                }
            }
        }
        stage('Push image') {
            steps {
                container('docker') {
                    script {
                        // Assume the Docker Hub registry by passing an empty string as the first parameter
                        docker.withRegistry('' , 'dockerhub') {
                            backendImage.push()
                            frontendImage.push()
                        }
                    }
                }
            }
        }
        stage('Deploy kubernetes') {
            steps {
                script {
                    withKubeConfig([credentialsId: 'kube-config']) {
                        sh 'kubectl delete ns deployment-booking'
                    }
                    kubernetesDeploy(kubeconfigId: "kube-config", configs: "kubernetes/namespace.yml")
                    kubernetesDeploy(kubeconfigId: "kube-config", configs: "kubernetes")
                }
            }
        }
    }
}
