apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-persistence
              mountPath: /var/jenkins_home
            - name: docker-access
              mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-persistence
          hostPath:
            path: /tmp/hostpath_pv/jenkins_home
        - name: docker-access
          hostPath:
            path: /var/run/docker.sock

---
apiVersion: v1
kind: "Service"
metadata:
  name: jenkins-service
  labels:
    name: jenkins-service
  annotations:
    description: Jenkins service
spec:
  type: NodePort
  ports:
    - name: jenkins
      port: 8080
      targetPort: 8080
      nodePort: 31112
      protocol: TCP
    - name: tunnel
      port: 50000
      targetPort: 50000
  selector:
    name: jenkins
  sessionAffinity: "None"