apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-configmap
data:
    booking.room.type: "double-bed-room"
    booking.room.name: "Luxury"
    booking.room.enterCode: "123456"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-configmap-file
data:
  application.properties: |
    booking.room.type="twin-bed-room"
    booking.room.name="Very Luxury"
    booking.room.enterCode="654321"