apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: ${K8S_NAMESPACE}
spec:
  ports:
    - name: frontend-service
      protocol: TCP
      port: 80
      targetPort: 80
    - name: backend-service
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: booking-app
---
apiVersion: v1
kind: "Service"
metadata:
  name: booking-postgres-service
  namespace: ${K8S_NAMESPACE}
  labels:
    name: booking-postgres-service
  annotations:
    description: Booking postgres
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 31111
      protocol: TCP
  selector:
    name: booking-postgres
  sessionAffinity: "None"