spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://booking-postgres-service:5432/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
    sql:
        init:
            mode: always